services:
    tas2580.privacyprotection.listener:
        class: tas2580\privacyprotection\event\listener
        arguments:
            - '@auth'
            - '@config'
            - '@config_text'
            - '@dbal.conn'
            - '@dispatcher'
            - '@user'
            - '@template'
            - '@request'
            - '@language'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
    tas2580.privacyprotection.cron.task.anonymize_ip:
        class: tas2580\privacyprotection\cron\task\anonymize_ip
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@log'
        calls:
            - [set_name, [tas2580.privacyprotection.cron.task.anonymize_ip]]
        tags:
            - { name: cron.task }